# <span style="color:brown">Project 2 : Ames Housing Data and Kaggle Challenge</span>
---
## <span style="color:Blue">Basic Home Value Data Grap</span>

#### Ryan McDonald, General Assembly
---

### Step 1: Reading the Data 
**Imports/ Read The Data**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("../datasets/project_data/clean_train.csv")
pd.set_option('display.max_columns', 75)
train.head()

,ms_subclass,lot_frontage,lot_area,overall_qual,overall_cond,year_built,year_remod/add,mas_vnr_area,bsmtfin_sf_1,bsmtfin_sf_2,bsmt_unf_sf,total_bsmt_sf,1st_flr_sf,2nd_flr_sf,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,bedroom_abvgr,kitchen_abvgr,totrms_abvgrd,fireplaces,garage_yr_blt,garage_cars,garage_area,wood_deck_sf,open_porch_sf,enclosed_porch,3ssn_porch,screen_porch,pool_area,mo_sold,yr_sold,saleprice,ms_zoning_RH,ms_zoning_RL,...,kitchen_qual_Gd,kitchen_qual_TA,functional_Maj2,functional_Min1,functional_Min2,functional_Mod,functional_Sal,functional_Sev,functional_Typ,garage_type_Attchd,garage_type_Basment,garage_type_BuiltIn,garage_type_CarPort,garage_type_Detchd,garage_finish_RFn,garage_finish_Unf,garage_qual_Fa,garage_qual_Gd,garage_qual_Po,garage_qual_TA,garage_cond_Fa,garage_cond_Gd,garage_cond_Po,garage_cond_TA,paved_drive_P,paved_drive_Y,sale_type_CWD,sale_type_Con,sale_type_ConLD,sale_type_ConLI,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_WD,total_baths,tot_fin_sq,home_age
0,60,68.0,13517,6,8,1976,2005,289.0,533.0,0.0,192.0,725.0,725,754,1479,0.0,0.0,2,1,3,1,6,0,1976.0,2.0,475.0,0,44,0,0,0,0,3,2010,130500,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.5,2012.0,34
1,60,43.0,11492,7,5,1996,1997,132.0,637.0,0.0,276.0,913.0,913,1209,2122,1.0,0.0,2,1,4,1,8,1,1997.0,2.0,559.0,0,74,0,0,0,0,4,2009,220000,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3.5,2759.0,13
2,20,68.0,7922,5,7,1953,2007,0.0,731.0,0.0,326.0,1057.0,1057,0,1057,1.0,0.0,1,0,3,1,5,0,1953.0,1.0,246.0,0,52,0,0,0,0,1,2010,109000,0,1,...,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.0,1788.0,57
3,60,73.0,9802,5,5,2006,2007,0.0,0.0,0.0,384.0,384.0,744,700,1444,0.0,0.0,2,1,3,1,7,0,2007.0,2.0,400.0,100,0,0,0,0,0,4,2010,174000,0,1,...,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.5,1444.0,4
4,50,82.0,14235,6,8,1900,1993,0.0,0.0,0.0,676.0,676.0,831,614,1445,0.0,0.0,2,0,3,1,6,0,1957.0,2.0,484.0,0,59,0,0,0,0,3,2010,138500,0,1,...,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1445.0,110

In [3]:
train.shape

(1995, 226)

### Producing various stats to utilize within the presentation

In [4]:
train['saleprice'].describe()

count      1995.000000
mean     180050.088221
std       73527.477268
min       12789.000000
25%      130000.000000
50%      162500.000000
75%      213000.000000
max      500000.000000
Name: saleprice, dtype: float64

In [5]:
# If you guessed within $5k of mean saleprice, you'd only 'guess' 
# correctly 139 times (6.9%)
train.query('174648<= saleprice <= 185451')

,ms_subclass,lot_frontage,lot_area,overall_qual,overall_cond,year_built,year_remod/add,mas_vnr_area,bsmtfin_sf_1,bsmtfin_sf_2,bsmt_unf_sf,total_bsmt_sf,1st_flr_sf,2nd_flr_sf,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,bedroom_abvgr,kitchen_abvgr,totrms_abvgrd,fireplaces,garage_yr_blt,garage_cars,garage_area,wood_deck_sf,open_porch_sf,enclosed_porch,3ssn_porch,screen_porch,pool_area,mo_sold,yr_sold,saleprice,ms_zoning_RH,ms_zoning_RL,...,kitchen_qual_Gd,kitchen_qual_TA,functional_Maj2,functional_Min1,functional_Min2,functional_Mod,functional_Sal,functional_Sev,functional_Typ,garage_type_Attchd,garage_type_Basment,garage_type_BuiltIn,garage_type_CarPort,garage_type_Detchd,garage_finish_RFn,garage_finish_Unf,garage_qual_Fa,garage_qual_Gd,garage_qual_Po,garage_qual_TA,garage_cond_Fa,garage_cond_Gd,garage_cond_Po,garage_cond_TA,paved_drive_P,paved_drive_Y,sale_type_CWD,sale_type_Con,sale_type_ConLD,sale_type_ConLI,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_WD,total_baths,tot_fin_sq,home_age
11,20,64.0,7488,7,5,2005,2005,0.0,393.0,0.0,815.0,1208.0,1208,0,1208,0.0,0.0,2,0,2,1,6,0,2005.0,2.0,632.0,105,58,0,0,0,0,2,2006,183600,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.0,1601.0,1
23,20,68.0,7980,6,7,1992,2007,0.0,935.0,0.0,233.0,1168.0,1187,0,1187,1.0,0.0,2,0,3,1,6,0,1992.0,2.0,420.0,483,21,0,0,0,0,3,2010,185000,0,1,...,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3.0,2122.0,18
37,20,80.0,9600,7,6,1973,1973,320.0,916.0,0.0,326.0,1242.0,1242,0,1242,0.0,0.0,1,1,3,1,6,1,1973.0,2.0,528.0,0,0,0,0,0,0,9,2007,175500,0,1,...,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1.5,2158.0,34
84,20,67.0,10083,7,5,2003,2003,0.0,833.0,0.0,343.0,1176.0,1200,0,1200,1.0,0.0,2,0,2,1,5,0,2003.0,2.0,555.0,0,41,0,0,0,0,8,2009,184900,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3.0,2033.0,6
88,80,68.0,11104,6,6,1969,1969,0.0,828.0,0.0,599.0,1427.0,1427,0,1427,0.0,1.0,2,0,4,1,7,0,1969.0,2.0,516.0,0,0,0,0,216,0,5,2008,183000,0,1,...,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.5,2255.0,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1950,160,24.0,2280,6,5,1999,1999,342.0,565.0,0.0,179.0,744.0,757,744,1501,1.0,0.0,2,1,3,1,6,1,1999.0,2.0,440.0,0,0,0,0,0,0,9,2007,176500,0,0,...,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3.5,2066.0,8
1959,120,34.0,5122,6,5,2005,2005,135.0,881.0,0.0,425.0,1306.0,1306,0,1306,1.0,0.0,2,0,1,1,5,1,2005.0,2.0,624.0,170,63,0,0,0,0,3,2009,184500,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3.0,2187.0,4
1963,60,100.0,10839,6,5,1997,1998,0.0,0.0,0.0,926.0,926.0,926,678,1604,0.0,0.0,2,1,3,1,7,1,1997.0,2.0,470.0,0,36,0,0,0,0,7,2008,181000,0,1,...,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.5,1604.0,11
1988,60,65.0,8453,6,5,1995,1995,38.0,362.0,0.0,392.0,754.0,754,855,1609,0.0,0.0,2,1,3,1,6,0,1995.0,2.0,525.0,0,70,0,0,0,0,4,2008,182000,0,1,...,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2.5,1971.0,13
1992,50,57.0,7558,6,6,1928,1950,0.0,0.0,0.0,896.0,896.0,1172,741,1913,0.0,0.0,1,1,3,1,9,1,1929.0,2.0,342.0,0,0,0,0,0,0,3,2009,177000,0,1,...,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1.5,1913.0,81

In [6]:
# Total Finished Sqft Stats
train['tot_fin_sq'].describe()

count    1995.000000
mean     1972.775940
std       697.363504
min       334.000000
25%      1490.000000
50%      1832.000000
75%      2376.500000
max      4958.000000
Name: tot_fin_sq, dtype: float64

In [7]:
# Total Baths (full and half baths combined) Stats
train['total_baths'].describe()

count    1995.000000
mean        2.220050
std         0.794255
min         1.000000
25%         2.000000
50%         2.000000
75%         2.500000
max         7.000000
Name: total_baths, dtype: float64

In [8]:
# Total Bedrooms Aboveground Stats
train['bedroom_abvgr'].describe()

count    1995.000000
mean        2.848120
std         0.821288
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         8.000000
Name: bedroom_abvgr, dtype: float64

In [9]:
# Age of Home Stats
train['home_age'].describe()

count    1995.000000
mean       35.726817
std        29.944232
min         0.000000
25%         7.000000
50%        34.000000
75%        54.000000
max       136.000000
Name: home_age, dtype: float64

In [11]:
sales_06 =train.loc[train['yr_sold']==2006]

In [12]:
# 2006 Sales Price Stats
sales_06['saleprice'].describe()

count       422.000000
mean     176691.933649
std       72572.774706
min       35000.000000
25%      130000.000000
50%      159250.000000
75%      209525.000000
max      475000.000000
Name: saleprice, dtype: float64

In [13]:
sales_07 =train.loc[train['yr_sold']==2007]

In [14]:
# 2007 Sales Price Stats
sales_07['saleprice'].describe()

count       487.000000
mean     183848.468172
std       73943.211773
min       39300.000000
25%      130000.000000
50%      166000.000000
75%      214500.000000
max      466500.000000
Name: saleprice, dtype: float64

In [15]:
sales_08 =train.loc[train['yr_sold']==2008]

In [16]:
# 2008 Sales Price Stats
sales_08['saleprice'].describe()

count       426.000000
mean     182491.342723
std       77041.109547
min       52000.000000
25%      130000.000000
50%      163000.000000
75%      218502.000000
max      475000.000000
Name: saleprice, dtype: float64

In [17]:
sales_09 =train.loc[train['yr_sold']==2009]

In [18]:
# 2009 Sales Price Stats
sales_09['saleprice'].describe()

count       436.000000
mean     180465.009174
std       73751.800091
min       37900.000000
25%      130000.000000
50%      163000.000000
75%      213000.000000
max      485000.000000
Name: saleprice, dtype: float64

In [19]:
sales_10 =train.loc[train['yr_sold']==2010]

In [20]:
# 2010 Sales Price Stats
sales_10['saleprice'].describe()

count       224.000000
mean     172668.169643
std       66640.512359
min       12789.000000
25%      128150.000000
50%      155000.000000
75%      206000.000000
max      500000.000000
Name: saleprice, dtype: float64

In [21]:
# Mean sales price change 2009-2010
(1-((sales_09['saleprice'].mean())/ (sales_10['saleprice'].mean())))*100

-4.515504824995609

In [22]:
# Mean sales price change 2008-2009
(1-((sales_08['saleprice'].mean())/ (sales_09['saleprice'].mean())))*100

-1.1228401328124082

In [23]:
# Mean sales price change 2007-2008
(1-((sales_07['saleprice'].mean())/ (sales_08['saleprice'].mean())))*100

-0.7436656606444103

In [24]:
# Mean sales price change 2006-2007
(1-((sales_06['saleprice'].mean())/ (sales_07['saleprice'].mean())))*100

3.892626680186051

In [25]:
# Mean Property Value Loss Per year
(-4.5155 + -1.1223 + -0.7436 + 3.8926) / 4

-0.6222000000000001